[package]
name = "distance-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
iced_futures = { version = "0.13.2", features = ["tokio"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
